# Logging level
logging:
  level:
    root: DEBUG

# JPA/Hibernate configuration for development
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Data source configuration for development
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftDrive_db
    username: postgres
    password: aidar


  # Enable/disable specific features
  devtools:
    restart:
      enabled: true
