# Logging level
logging:
  level:
    root: DEBUG

# JPA/Hibernate configuration for development
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Data source configuration for development
  datasource:
    url: jdbc:h2:file:./swiftRide_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  # H2 console configuration for development
  h2:
    console:
      enabled: true
      path: /h2-console

  # Enable/disable specific features
  devtools:
    restart:
      enabled: true
